/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import biblioteca.Aluno;
import biblioteca.Controle;
import biblioteca.Livro;
import controle.AlunoControl;
import controle.EmprestimoControl;
import controle.LivroControl;
import dao.Dao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Emprestimo;
import modelo.Item;

/**
 *
 * @author BrunoPC
 */
public class Interface extends javax.swing.JFrame {
    List<modelo.Livro> livros = new ArrayList<modelo.Livro>();
    DefaultListModel listaAlunos = new DefaultListModel();
    DefaultListModel listaLivros = new DefaultListModel();
    

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_buscaAluno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jb_cadastrarAluno = new javax.swing.JButton();
        jb_inserir_livro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlunos = new javax.swing.JList<String>();
        jLabel3 = new javax.swing.JLabel();
        jb_reservar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextLivros = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLivros = new javax.swing.JList<String>();
        jTextRaAluno = new javax.swing.JTextField();
        jb_devolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_buscaAluno.setText("Buscar Aluno");
        jb_buscaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscaAlunoActionPerformed(evt);
            }
        });

        jLabel6.setText("Livros");

        jb_cadastrarAluno.setText("Cadastrar Aluno");
        jb_cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarAlunoActionPerformed(evt);
            }
        });

        jb_inserir_livro.setText("Inserir");
        jb_inserir_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inserir_livroActionPerformed(evt);
            }
        });

        jListAlunos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListAlunos);

        jLabel3.setText("Aluno");

        jb_reservar.setText("Reservar");
        jb_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reservarActionPerformed(evt);
            }
        });

        jLabel4.setText("Reserva");

        jLabel5.setText("Nome do Aluno:");

        jLabel7.setText("Digite o código do livro desejado:");

        jLabel8.setText("RA do Aluno:");

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        jListLivros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListLivros);

        jb_devolver.setText("Devolver");
        jb_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_devolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jb_buscaAluno)
                .addGap(18, 18, 18)
                .addComponent(jb_cadastrarAluno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextRaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_inserir_livro)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(44, 44, 44))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jb_reservar)
                                .addGap(40, 40, 40)
                                .addComponent(jb_devolver)))
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextRaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscaAluno)
                    .addComponent(jb_cadastrarAluno))
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_inserir_livro)
                    .addComponent(jTextLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_reservar)
                            .addComponent(jb_devolver))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int counter = 0;
    private void jb_buscaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscaAlunoActionPerformed
        // TODO add your handling code here:
        
        String nomeAluno = jTextNome.getText();
        try {
            Integer raAluno = Integer.parseInt(jTextRaAluno.getText());
            //Controle c = new Controle();
            AlunoControl ac = new AlunoControl();
            modelo.Aluno aux = ac.checaAluno(raAluno);
            if(aux!=null){
                listaAlunos.removeAllElements();
                listaAlunos.addElement(aux);
                //listaAlunos.add(counter, aux);
                counter++;
                jListAlunos.removeAll();
                jListAlunos.setModel(listaAlunos);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Aluno Inexistente");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Preencha o RA do aluno!");
        }
        
        
        

    }//GEN-LAST:event_jb_buscaAlunoActionPerformed
    int cont = 0;
    private void jb_inserir_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inserir_livroActionPerformed
        try {
            Integer codLivro = Integer.parseInt(jTextLivros.getText());
            LivroControl lc = new LivroControl();
            modelo.Livro l = lc.checaLivro(codLivro);
            if(!checaLivro(codLivro)){
                if(l==null){ 
                    JOptionPane.showMessageDialog(null, "Livro nao existente será criado e adicionado");
                    if(lc.inserirLivro(codLivro)){
                        JOptionPane.showMessageDialog(null, "Livro adicionado!");
                        l = lc.checaLivro(codLivro);
                    }
                }
                livros.add(l);
                listaLivros.add(cont,l);
                cont++;
                jListLivros.removeAll();
                jListLivros.setModel(listaLivros);
            }else{
                JOptionPane.showMessageDialog(null, "Livro ja inserido!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite o código do livro!");
        }
        
        

    }//GEN-LAST:event_jb_inserir_livroActionPerformed
    private boolean checaLivro(int id){
        for(modelo.Livro l : livros){
            if(l.getCodigo()==id) return true;
        }
        return false;
    }
    
    private void jb_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reservarActionPerformed
        
        try {
            Dao<modelo.Aluno> dao = new Dao(modelo.Aluno.class);
            Integer index = jListAlunos.getSelectedIndex();
            modelo.Aluno a = (modelo.Aluno)listaAlunos.getElementAt(index);
            AlunoControl c = new AlunoControl();
            modelo.Aluno a1 = new modelo.Aluno(a.getNome(),a.getRA());
            if(c.verificaDebito(a1.getRA())){
                JOptionPane.showMessageDialog(null, "Aluno em débito!");
            }
            else{
                //System.out.println("your own personal jesus");
                try {
                    if(c.emprestar(a1, livros)) {
                        EmprestimoControl ec = new EmprestimoControl();
                        Emprestimo e = ec.checaEmprestimo(a1.getRA());
                        JOptionPane.showMessageDialog(null, "Empréstimo realizado com sucesso!"
                                + "\nData Devolução:" +e.getDataPrevista());
                        c.alteraDebito(a1);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Deve haver pelo menos 1 livro para efetuar a reserva.");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Apenas uma reserva por pessoa permitida!");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um aluno!");
        }
        
        
    }//GEN-LAST:event_jb_reservarActionPerformed

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jb_cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarAlunoActionPerformed
        String nomeAluno = jTextNome.getText();
        String ra = jTextRaAluno.getText();
        AlunoControl ac = new AlunoControl();
        try {
            Integer raAluno = Integer.parseInt(jTextRaAluno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "RA somente números!");
        }
        
        if(nomeAluno.isEmpty() || ra.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nome e RA DEVEM estar preenchidos!");
        }else{
            Integer raAluno = Integer.parseInt(jTextRaAluno.getText());
            if(ac.checaAluno(raAluno)!=null){
                JOptionPane.showMessageDialog(null, "RA ja esta sendo usado!");
            }
            else{
                if(ac.inserirAluno(raAluno,nomeAluno)) JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                else JOptionPane.showMessageDialog(null, "Erro ao cadastrar novo aluno.");
            }
            
        }
    }//GEN-LAST:event_jb_cadastrarAlunoActionPerformed

    private void jb_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_devolverActionPerformed
        //Dao<modelo.Aluno> dao = new Dao(modelo.Aluno.class);
        try {
            Integer index = jListAlunos.getSelectedIndex();
            modelo.Aluno a = (modelo.Aluno)listaAlunos.getElementAt(index);
            EmprestimoControl ec = new EmprestimoControl();

            modelo.Aluno a1 = new modelo.Aluno(a.getNome(),a.getRA());

            Emprestimo e = ec.checaEmprestimo(a1.getRA());

            if(e!=null && e.isAtivo()){
                InterfaceDevolucao i = new InterfaceDevolucao(e,a1);
                i.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Não há reservas para este RA!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum aluno selecionado");
        }
        
    }//GEN-LAST:event_jb_devolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListAlunos;
    private javax.swing.JList<String> jListLivros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextLivros;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextRaAluno;
    private javax.swing.JButton jb_buscaAluno;
    private javax.swing.JButton jb_cadastrarAluno;
    private javax.swing.JButton jb_devolver;
    private javax.swing.JButton jb_inserir_livro;
    private javax.swing.JButton jb_reservar;
    // End of variables declaration//GEN-END:variables
}
