/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import biblioteca.Aluno;
import biblioteca.Controle;
import biblioteca.Livro;
import controle.AlunoControl;
import controle.LivroControl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author BrunoPC
 */
public class Interface extends javax.swing.JFrame {
    List<modelo.Livro> livros = new ArrayList<modelo.Livro>();
    DefaultListModel listaAlunos = new DefaultListModel();
    DefaultListModel listaLivros = new DefaultListModel();
    

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_buscaAluno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jb_cadastrarAluno = new javax.swing.JButton();
        jb_inserir_livro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlunos = new javax.swing.JList<String>();
        jLabel3 = new javax.swing.JLabel();
        jb_reservar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextLivros = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLivros = new javax.swing.JList<String>();
        jTextRaAluno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_buscaAluno.setText("Buscar Aluno");
        jb_buscaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscaAlunoActionPerformed(evt);
            }
        });

        jLabel6.setText("Livros");

        jb_cadastrarAluno.setText("Cadastrar Aluno");
        jb_cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarAlunoActionPerformed(evt);
            }
        });

        jb_inserir_livro.setText("Inserir");
        jb_inserir_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inserir_livroActionPerformed(evt);
            }
        });

        jListAlunos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListAlunos);

        jLabel3.setText("Aluno");

        jb_reservar.setText("Reservar");
        jb_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reservarActionPerformed(evt);
            }
        });

        jLabel4.setText("Reserva");

        jLabel5.setText("Nome do Aluno:");

        jLabel7.setText("Digite o código do livro desejado:");

        jLabel8.setText("RA do Aluno:");

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        jListLivros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListLivros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jb_buscaAluno)
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(jb_reservar)
                    .addGap(213, 213, 213))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(144, 144, 144))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextRaAluno))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addComponent(jb_cadastrarAluno)))
                    .addGap(126, 126, 126))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(224, 224, 224))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jb_inserir_livro)))
                    .addGap(96, 96, 96)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jb_buscaAluno)
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextRaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jb_cadastrarAluno)
                    .addGap(7, 7, 7)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_inserir_livro))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addGap(4, 4, 4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jb_reservar)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int counter = 0;
    private void jb_buscaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscaAlunoActionPerformed
        // TODO add your handling code here:
        String nomeAluno = jTextNome.getText();
        Integer raAluno = Integer.parseInt(jTextRaAluno.getText());
        //Controle c = new Controle();
        AlunoControl ac = new AlunoControl();
        modelo.Aluno aux = ac.checaAluno(raAluno);
        if(aux!=null){
            listaAlunos.removeAllElements();
            listaAlunos.addElement(aux);
            //listaAlunos.add(counter, aux);
            counter++;
            jListAlunos.removeAll();
            jListAlunos.setModel(listaAlunos);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Aluno Inexistente");
        }

    }//GEN-LAST:event_jb_buscaAlunoActionPerformed
    int cont = 0;
    private void jb_inserir_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inserir_livroActionPerformed
        // TODO add your handling code here:
        Integer codLivro = Integer.parseInt(jTextLivros.getText());
        //Controle c = new Controle();
        LivroControl lc = new LivroControl();
        //Livro aux = c.inserirLivro(codLivro);

        //List<Livro> livros = new ArrayList<Livro>();
        /*Livro l = new Livro(codLivro);
        if(!checaLivro(codLivro)){
            livros.add(l);
            if(!c.buscaLivros(l)){
                JOptionPane.showMessageDialog(null, "Livro não existente será adicionado");
                c.adicionaLivro(l);
            }
            listaLivros.add(cont, l);
            cont++;
            jListLivros.removeAll();
            jListLivros.setModel(listaLivros);
        }*/
        modelo.Livro l = lc.checaLivro(codLivro);
        if(!checaLivro(codLivro)){
            if(l==null){ 
                JOptionPane.showMessageDialog(null, "Livro nao existente será criado e adicionado");
                if(lc.inserirLivro(codLivro)){
                    JOptionPane.showMessageDialog(null, "Livro adicionado!");
                    l = lc.checaLivro(codLivro);
                }
            }
            livros.add(l);
            listaLivros.add(cont,l);
            cont++;
            jListLivros.removeAll();
            jListLivros.setModel(listaLivros);
        }else{
            JOptionPane.showMessageDialog(null, "Livro ja inserido!");
        }
        
        /*if(aux != null){

            listaLivros.add(cont, aux);
            cont++;
            jListLivros.removeAll();
            jListLivros.setModel(listaLivros);
        }*/
        //System.out.println(aux);

    }//GEN-LAST:event_jb_inserir_livroActionPerformed
    private boolean checaLivro(int id){
        for(modelo.Livro l : livros){
            if(l.getCodigo()==id) return true;
        }
        return false;
    }
    
    private void jb_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reservarActionPerformed
        Integer index = jListAlunos.getSelectedIndex();
        Aluno a = (Aluno)listaAlunos.getElementAt(index);
        Controle c = new Controle();
        if(c.verificaDebitoAluno(a.getRA())){
            JOptionPane.showMessageDialog(null, "Aluno em débito!");
        }
        else{
            //if(c.emprestarInterface(a, livros)) JOptionPane.showMessageDialog(null, "Empréstimo realizado com sucesso!");
        }
        
    }//GEN-LAST:event_jb_reservarActionPerformed

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jb_cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarAlunoActionPerformed
        String nomeAluno = jTextNome.getText();
        String ra = jTextRaAluno.getText();
        AlunoControl ac = new AlunoControl();
        try {
            Integer raAluno = Integer.parseInt(jTextRaAluno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "RA somente números!");
        }
        
        /*if(c.cadastrarAluno(nomeAluno, raAluno)!=null){
            JOptionPane.showMessageDialog(null, "Aluno Cadastrado");
        }else{
            JOptionPane.showMessageDialog(null, "Aluno já existe");
        }*/
        
        if(nomeAluno.isEmpty() || ra.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nome e RA DEVEM estar preenchidos!");
        }else{
            Integer raAluno = Integer.parseInt(jTextRaAluno.getText());
            if(ac.checaAluno(raAluno)!=null){
                JOptionPane.showMessageDialog(null, "RA ja esta sendo usado!");
            }
            else{
                if(ac.inserirAluno(raAluno,nomeAluno)) JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                else JOptionPane.showMessageDialog(null, "Erro ao cadastrar novo aluno.");
            }
            
        }
    }//GEN-LAST:event_jb_cadastrarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListAlunos;
    private javax.swing.JList<String> jListLivros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextLivros;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextRaAluno;
    private javax.swing.JButton jb_buscaAluno;
    private javax.swing.JButton jb_cadastrarAluno;
    private javax.swing.JButton jb_inserir_livro;
    private javax.swing.JButton jb_reservar;
    // End of variables declaration//GEN-END:variables
}
